### ISSUE TITLE
Chart when overflow parent contaier

### ISSUE THREAD

**Issue by sekmentina** [amcharts/amcharts5#20] opened 2021-09-28 13:52 UTC
Hi!

Looks like the chart will register mouse events even when overflow parent container.

example:
https://stackblitz.com/edit/js-n9il79

**Comment by martynasma** [comment] 2021-09-28 14:04
Might be duplicate of this: https://github.com/amcharts/amcharts5/issues/11 (fixed in 5.0.0-beta.20)

**Comment by SekMENtina** [comment] 2021-09-28 16:55
Still happening
@martynasma 
https://jsfiddle.net/Sekmentina/j9t8gaxw/17/

**Comment by martynasma** [comment] 2021-10-01 11:04
Fixed in [5.0.0-beta.29](https://github.com/amcharts/amcharts5/releases/tag/5.0.0-beta.29).

## [5.0.0-beta.29] - 2021-10-01

### Added
- Wherever date or number format can be set (`DateFormatter`, `NumberFormatter`, `DateAxis`, `ValueAxis`, `Exporting`) it can now be set as `Intl.DateTimeFormatOptions` (for date format) or `Intl.NumberFormatOptions` (for number format) object in additional to string-based format. [More info](https://www.amcharts.com/docs/v5/tutorials/formatting-date-time-and-numbers-using-intl-object/).
- New list type `ListAutoDispose` added.

### Changed
- `XYCursor` will now ignore mouse movement if chart is obstructed by other element, unless zoomin/panning.
- `series`, `xAxes`, and `yAxes` on an `XYChart` are now `ListAutoDispose`, which means that removing items from those lists will automatically dispose them. Set `autoDispose = false` on those lists if you are planning on removing and reusing items.

### Fixed
- `Sunburst` nodes were shown on drill-down when they were not supposed to in some cases.
- `Hierarchy` node elements were ignoring `templateField`.
- It was impossible to move `XYChart` scrollbars to some other container.
- Fixed memory leaking when scrolling `LineSeries`, and when disposing series or other items.
- `XYCursor` was not firing `selectended` event if `behavior` was set to `"selectX"`, `"selectY"`, or `"selectXY"`.
- `XYCursor` was hiding selection when when behavior was set to `"selectX"`, `"selectY"`, or `"selectXY"`.
- `SerialChart.series.clear()` was not working properly.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download-v5/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2021-10-01 11:04 UTC
Labels: bug, in next release
