### ISSUE TITLE
Problem With Drawing Tools (Ellipse)

### ISSUE THREAD

**Issue by mukeshbadgujar** [amcharts/amcharts5#591] opened 2022-09-01 05:35 UTC
Steps to create problem/bug:

1. open drawing tool
2. select line
3. draw line anywhere on chart.
4. also draw ellipse by selecting from drawing tool
5. now click on drawing tool to disable drawing
6. (now drawing tool is off) 
7. now click on any point of line (it allows you to draw new line from that point), now draw this this line. (i don't know it is feature or a bug)
8. now follow same for ellipse, click on any point of ellipse (it allows you to draw new ellipse from that point)
9. now you cant able to plot the ellipse, it always sticks to the pointer.
10. now if you still want to draw the ellipse, then again click on any point of ellipse.

code: https://jsfiddle.net/hagrLus0/

# I have checked this for Ellipse, please check this with all other drawing controls.

**Comment by mukeshbadgujar** [comment] 2022-09-02 07:04
@martynasma Please look out the bug

**Comment by martynasma** [comment] 2022-09-02 09:35
This behavior is by design.

**Comment by mukeshbadgujar** [comment] 2022-09-02 09:45
Clicking on ellipse points gives problem, new ellipse cant able to plot, it just sticks to the cursor movement.

please check

**Comment by mukeshbadgujar** [comment] 2022-09-02 10:19
Same Problem With Quadrant Line


https://user-images.githubusercontent.com/32473209/188118709-1af9ddfc-2fc9-4e2f-9e72-3f1cb5204acf.mp4

**Comment by zeroin** [comment] 2022-09-02 11:13
We will fix this in next release, thank you.

**Comment by martynasma** [comment] 2022-09-05 15:06
Fixed in [5.2.20](https://github.com/amcharts/amcharts5/releases/tag/5.2.20).

## [5.2.20] - 2022-09-05

### Added
- All indicator series will now have `"indicator"` theme tag set. Detect indicator series via `series.hasTag("indicator")`.
- `autoZoom` added to `ValueAxis` (default: `true`). If set to `false`, the axis won't be auto-zoomed to a selection (this works only if the other axis is a `DateAxis` or a `CategoryAxis`). This setting will be ignored if both X and Y axes are a `ValueAxis`.
- `StandardDeviation` indicator added.

### Changed
- Series edit modal on a `StockChart` would show incorrect controls if the main chart series was a `LineSeries`.

### Fixed
- Initial sizing of HTML tooltips fixed (again).
- Exporting a chart in a `<div>` with `height: auto` was not working properly.
- If a point in a `LineSeries` was way out of bounds (million times further than the bounds of plot area), the line could disappear.
- In some cases, if chart was using loadable fonts, it could go into non-stop flickering mode.
- `StockChart` with drawing mode disabled could start drawing new objects if clicked on points of an old drawing.
- `PointedRectangle`, mostly used by a `Tooltip` was drawn incorrectly if its stem size was bigger than height. 
- Removing a `QuadrantLineSeries` drawing from a `StockChart` resulted an error.
- It was impossible to delete `Fibonacci` or `FibonacciTimezone` drawings one by one after switching to another drawing tool.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2022-09-05 15:06 UTC
Labels: bug, in next release
