### ISSUE TITLE
How to sync axis widths across multiple charts when chart is ready

### ISSUE THREAD

**Issue by datafoo** [amcharts/amcharts5#313] opened 2022-03-01 07:24 UTC
This is a follow up question to https://github.com/amcharts/amcharts5/issues/309. I am trying to [sync the axis widths across multiple charts](https://www.amcharts.com/docs/v5/tutorials/syncing-axis-widths-across-multiple-charts/) but only when chart [is ready](https://www.amcharts.com/docs/v5/getting-started/root-element/#chart-ready-event).

I have tried with the codepen https://codepen.io/jackfoo/pen/zYPMxgp but that does not do anything despite the console logging the correct values.

When I change line 119 to set `width` instead of `minWidth`, then it works. Why doesn't it work with `minWidth`?

**Comment by martynasma** [comment] 2022-03-01 11:03
Your CodePen does work for me even with `minWidth`:

![image](https://user-images.githubusercontent.com/1458520/156157664-a08ceeff-cc8e-48a4-a4fb-5d4e8734fa69.png)

Maybe it's a browser thing. Which one are you using?

**Comment by datafoo** [comment] 2022-03-01 11:32
I have tested on Windows 10 with:

- Microsoft Edge 98.0.1108.62
- Firefox 97.0.1
- Chrome 98.0.4758.102

and they all have the problem like in your screenshot.

Here is the problem:
![actual](https://user-images.githubusercontent.com/34766150/156161682-6847cf03-c7ba-463a-81a2-28aeec945bd3.png)

Here is the expected:
![expected](https://user-images.githubusercontent.com/34766150/156161701-a03d8308-d7ed-4415-96db-9dfb1fecb240.png)

**Comment by datafoo** [comment] 2022-03-01 11:35
I have noticed that changing the view on Code Pen, or resizing the height of the windows triggers the axis synchronization.

**Comment by sassomedia** [comment] 2022-03-02 10:31
Indeed, CodePen is a bit misleading. The issue is easily reproducible (I'm using Safari 15.3, fyi) once the automatic refresh is disabled and you use manual refresh instead.

I'm not sure why `minWidth` does not immediately update but compared to the [original example](https://codepen.io/team/amcharts/pen/gOXjWVe?editors=0010) with the `boundschanged` event that fires multiple times, the `frameended` event only fires once. Maybe `minWidth` does not automatically redraw like when `width` is set?

I did get the `minWidth` to work though by forcing the label to redraw with `appear()` after the `minWidth` was set. Note: also clearing the `text` was necessary as the `ghostLabel` contains the axis' highest value in text:
https://codepen.io/sassomedia/pen/QWOJXxB?editors=0010

@martynasma Is there a better way to redraw an item without using `appear()`? Might be helpful to add a public `redraw` method to the Sprite that just redraws it with the item's current properties. `appear()` inevitably reveals a hidden item.

**Comment by martynasma** [comment] 2022-03-03 09:45
@sassomedia In case of Axis, one of these two might work to trigger a redraw: `markDirty()` or `markDirtyValues()`.

**Comment by datafoo** [comment] 2022-03-03 14:10
> I'm not sure why `minWidth` does not immediately update

So you can reproduce the problem. This issue seems to be more a bug than a question at the end.

Will this be fixed?

**Comment by sassomedia** [comment] 2022-03-03 15:57
> In case of Axis, one of these two might work to trigger a redraw: markDirty() or markDirtyValues().

Yup, I had tried the different markDirty's (markDirty, markDirtySize, markDirtyValues) but those don't work. I was only able to get `appear` to work.

**Comment by martynasma** [comment] 2022-03-10 13:43
Fixed in [5.1.8](https://github.com/amcharts/amcharts5/releases/tag/5.1.8).

## [5.1.8] - 2022-03-10

### Added
- Settings `pinchZoomX` and `pinchZoomY` (defaults: `false`) added to `XYChart`. If set to `true` will allow pinch-zooming of a chart on touch devices. NOTE: these settings are not supported on `RadarChart`.
- `topPlotContainer` added to `XYChart`. It's a `Container` that can be used to place element over plot area.

### Changed
- The types for adapters has been changed to be more intuitive and useful. ([Issue 312](https://github.com/amcharts/amcharts5/issues/312))
- Tapping an element on a touch device will now generate `pointerover` event in addition to `click`. When tapped somewhere else, `pointerout` event will be triggered.

### Fixed
- Fixing ES6 module detection by BundlePhobia again ([Issue 294](https://github.com/amcharts/amcharts5/issues/294)).
- Pinch-zooming of a `MapChart` was not working well in some cases.
- `maxHeight` setting in `Sprite` was not working.
- Change of `minWidth` was not being applied at once, only if some other changes triggered chart to be redrawn.
- Changing or not setting data on an existing `FlowChart` was resulting in a JS error.
- `maxPanOut` setting in `MapChart` was not working.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2022-03-10 13:43 UTC
Labels: bug, in next release
