### ISSUE TITLE
Overflow hidden ForceDirected 

### ISSUE THREAD

**Issue by vueDevInci** [amcharts/amcharts5#1116] opened 2023-10-02 12:58 UTC
I am using ForceDirected mind map. Here when map overflow, it is not showing any scroll. Also it always get cut off from start.
I also want to hide animation but it always get applied.

**Comment by martynasma** [comment] 2023-10-03 05:53
Duplicate of https://github.com/amcharts/amcharts5/issues/546

**Closed by martynasma** 2023-10-03 05:53 UTC
Labels: duplicate
