### ISSUE TITLE
rtl mode not working on amcharts5 v.5.2

### ISSUE THREAD

**Issue by moonrider441** [amcharts/amcharts5#403] opened 2022-04-30 06:19 UTC
Hi. i have problem with rtl mode. i searched in old issues and the problem does not solved.
i create stack and line charts.
tooltip text has problem on rtl mode.
i'm working with laravel 8 and metronic 8 and amcharts 5.2

this is my tooltip codes:
`series.columns.template.setAll({
      tooltipText: "[bold]{name}:[/] {valueY}",
      tooltip: am5.Tooltip.new(root, {
          direction: "rtl",
          textAlign: "center"
      })
  });`
 
i set `root.rtl = true` too but not working.

plz help me.
could you tell me where i'm coding wrong ?

**Comment by martynasma** [comment] 2022-05-02 06:22
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by moonrider441** [comment] 2022-05-02 10:55
i created jsfiddle test for you.
plz pay attention when we use rtl in html tag this problem is showing.

[https://jsfiddle.net/moonrider441/nL2zp4fm/30/](url)

**Comment by martynasma** [comment] 2022-05-02 12:14
There's no `rtl` setting on Root element.

You need to set it directly to label:

```JavaScript
	var tooltip = am5.Tooltip.new(root, {
    //direction: "rtl",
    textAlign: "center",
    centerX: am5.percent(96)
  });
  
  tooltip.label.setAll({
  	direction: "rtl"
  })
  
  series.columns.template.setAll({
    tooltipText: "{name}: {valueY}",
    tooltip: tooltip
  });
```

That being said, there's still an issue with RTL where in-line formatting is being used with mixed RTL and LTR strings.

We will be looking into it.

In the interim, I suggest to not use in-line formatting for correct display of mixed content in tooltips.

**Comment by martynasma** [comment] 2022-06-20 07:04
I can't seem to be able to reproduce the issue of mixed content that I mentioned before. Closing.

**Closed by martynasma** 2022-06-20 07:04 UTC
Labels: bug

**Comment by moonrider441** [comment] 2022-06-20 07:39
@martynasma hi and tnx for your supporting.

Could you tell me that this issue is fixed ?

**Comment by martynasma** [comment] 2022-06-20 08:21
We did a lot of fixing since originally post here. What was misbehaving in my original tests, is now OK. If you find something that doesn't work, please feel free to reopen and provide a CodePen/jsFiddle for the issue.
