### ISSUE TITLE
LineSeries bullet alignment is off in Legend when JSON parsing

### ISSUE THREAD

**Issue by davidjb** [amcharts/amcharts5#1148] opened 2023-10-27 01:21 UTC
**Bug description**

When setting up a LineSeries and Bullets with JSON parsing, the symbol shown in the Legend appears incorrectly, with the alignment of the bullet, whilst the bullets appear correctly on the chart:

https://jsfiddle.net/eyz0qksb/

<img width="806" alt="image" src="https://github.com/amcharts/amcharts5/assets/1002811/8ebd9d00-3c4b-4125-bbba-a2f60a122e2e">

**Environment (if applicable)**

 - amCharts version: latest from CDN (5.5.1)
 - Browser: tested in Firefox 119, Chrome 118 and Safari 17
 - Vanilla JS

**Additional context**

The issue doesn't appear to affect bullets when created manually using JavaScript, so the issue appears to be with the JSON parsing.

**Comment by martynasma** [comment] 2023-10-31 08:35
This is caused by the "delayed" push of the fully-created chart to `root.container.children`. The bullets are created before they have a chance to inherit default theme from `Root` element.

Exactly the same issue as with [your other ticket](https://github.com/amcharts/amcharts5/issues/1158#issuecomment-1786708022).

We'll try to figure out if there's any way around it, and will keep you posted.

**Comment by martynasma** [comment] 2023-11-17 16:06
Fixed in [5.5.7](https://github.com/amcharts/amcharts5/releases/tag/5.5.7).

## [5.5.7] - 2023-11-17

### Added
- Two new settings on a `ClusteredPointSeries`: `scatterDistance` and `scatterRadius`. Allow exploding clusters of very close points when further zoom-in is no longer possible. [More info](https://www.amcharts.com/docs/v5/charts/map-chart/clustered-point-series/#Scatter_settings).

### Fixed
- `PieSeries` was not issuing proper colors for its slices with some JSON config setups.
- In `StockChart` when percent mode was being switched off and related series toggled via legend, it would revert to percent mode.
- When updating data on a `PieSeries` its ticks could be displayed going all the way to the center briefly.
- Changing data on a main series in a `StockChart` was not updating related indicators properly.
- Legend marker for a `LineSeries` with bullets could display incorrectly if the whole chart was created before adding it to the `Root` container.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2023-11-17 16:06 UTC
Labels: bug, in next release
