### ISSUE TITLE
Logarithmic is not working when i switch from Regular on Y axis scale settings in stock chart

### ISSUE THREAD

**Issue by rafee11** [amcharts/amcharts5#819] opened 2023-02-23 14:07 UTC
In stock chart, Logarithmic is not working properly when I switch from Regular to Logarithmic on Y axis scale setting. It is in blank as attached screenshot here

![image](https://user-images.githubusercontent.com/23078836/220930535-bb608b61-102d-4405-955b-bc6ed07a397f.png)

I am using amcharts v5.2.47

**Comment by zeroin** [comment] 2023-02-23 15:51
Could it be that your data has zero values or values less than zero?

**Comment by rafee11** [comment] 2023-02-23 15:57
@zeroin  There is no zero or less than zero values. It shows the chart when I switch the mode frequently as attached screenshot here 
![image](https://user-images.githubusercontent.com/23078836/220960610-c137e437-7ed4-416c-8701-b5662a18796c.png)

I can able to reproduce the issue when I switch from Regular to Logarithmic alone

**Comment by rafee11** [comment] 2023-03-02 08:26
@zeroin  I can able to reproduce the same issue on this link https://www.amcharts.com/demos/stock-chart-comparing-prices/, when we keep changing the y axis scale from regular to logarithmic 
![image](https://user-images.githubusercontent.com/23078836/222371829-f266804b-5bd1-467b-8b50-3ffa16f2c1da.png). 

I will also work on the codepen to share the same issue on my end. 

FYI I didn't configure or modify anything related to logarithmic on code level for y axis scale.

**Comment by amcharts** [comment] 2023-03-02 14:33
In your case, does it happen each time you do a switch?
As on our demo I was unable to reproduce it even though I tried a lot of times.

**Comment by rafee11** [comment] 2023-03-24 14:43
Yes in my case it happens frequently whenever I switch from regular to logarithmic. Add comparison series and try the same as attached on this video.

https://user-images.githubusercontent.com/23078836/227556585-c9a54457-9886-4f87-829a-b9f0c9813b71.mp4

**Comment by martynasma** [comment] 2023-03-31 11:11
Fixed in [5.3.9](https://github.com/amcharts/amcharts5/releases/tag/5.3.9).

## [5.3.9] - 2023-03-31

### Added
- New `PeriodSelector` setting: `hideLongPeriods`. Indicates whether to hide buttons for periods that are longer than the actual data on chart.
- New `DrawingControl` methods: `clearDrawings()` and `setEraser(true | false)`.
- Methods `hide()` and `show()` will now properly hide and show any indicator.
- `MapChart` methods `zoomToGeoPoint()` and `zoomToGeoBounds()` now accepts `rotationX` and `rotationY` parameters. If provided, the map not only zoom to the provided point/bounds but will rotate so that this point/bounds would be in the center. Mostly usefull with `geoOrthographic` projection.
- `MapChart`'s `convert()` method now accepts `rotationX` and `rotationY` optional parameters. If provided, the calculations will be done as if map is rotated by provided values.
- `MapPolygonSeries` / `MapPointSeries` method `zoomToDataItem()` now accepts an optional boolean `rotate` parameter. If it's `true`, the map will rotate so that this point/polygon would be in the center. Mostly useful with `geoOrthographic` projection.

### Changed
- Hiding a `StockPanel` via its `hide()` method will now animate it to size 0 before hiding completely.

### Fixed
- The scale of the `StockChart` could become incorrect if there were compared series and the scale was switched back and forth between logarithmic and regular.
- HTML-based tooltips were sized incorrectly in some cases.
- Setting `pointerOrientation` on a `Tooltip` was not updating an already visible tooltip.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2023-03-31 11:11 UTC
Labels: bug, in next release
