### ISSUE TITLE
Force directed graph doesn't has zoomable properties .

### ISSUE THREAD

**Issue by Amitnaresh29** [amcharts/amcharts5#734] opened 2022-12-28 04:31 UTC
**Question**

**Environment (if applicable)**

**Additional context**

Force directed graph doesn't has zoomable properties ,it was there in amcharts 4 but not in amcharts 5.

**Comment by martynasma** [comment] 2022-12-28 06:12
Duplicate of https://github.com/amcharts/amcharts5/issues/216

**Closed by martynasma** 2022-12-28 06:12 UTC
Labels: duplicate
