### ISSUE TITLE
Zoom reverts back automatically for one series in multi-series chart

### ISSUE THREAD

**Issue by tapiamcclung** [amcharts/amcharts5#1563] opened 2024-06-07 17:21 UTC
I have an `XYChart` that combines `LineSeries` with only bullets with a heatmap using `ColumnSeries`. These series are using different axes. Chart is setup with `wheelY: "zoomXY"`, but when I zoom by scrolling the wheel, the bullets seem to reach a maximum zoom level and return to the initial one, while the heatmap stays in the reached zoom.
I have tried setting`syncWithAxis` and `baseAxis` values but makes no difference.
I am attaching a gif of this behavior.

![firefox_3hsEW5yXrr](https://github.com/amcharts/amcharts5/assets/7925327/4200b808-762a-4706-949d-6a4daad1ee39)

Any ideas would be greatly appreciated. Thanks!
I am using amcharts v5.

Edit: I just found something similar happens in the [scatter chart example ](https://www.amcharts.com/demos/scatter-chart/) when zooming by scrolling with the mouse wheel.

**Comment by zeroin** [comment] 2024-06-10 09:09
The zooming problem can be fixed by adding `autoZoom: false` for both x and y axes, I added this to our examples. But I am not sure if that will fix all your problems, let us know if it wont.

**Comment by tapiamcclung** [comment] 2024-06-11 16:45
Unfortunately it doesn't. After adding `autoZoom: false` to the axes, the chart becomes unresponsive. The cursor doesn't move anymore and I cannot zoom in, out, or pan.
I'm curious that the docs say that the autoZoom setting will be ignored if both X and Y axes are a ValueAxis, which is the case of the example, but it works.
Could it be the combination of `ValueAxis` for the bullets and the `CategoryAxis` for the heatmap that is causing the issue?

**Comment by tapiamcclung** [comment] 2024-06-11 16:57
Thanks. It works for the most part. If I zoom in too much, layers seem to come out of sync, and return to their normal state when I fully zoom out. 
But it is much better than the previous behavior. 
I'm curious that the `ValueAxis` docs state that if autoZoom is set to false, the axis won't be auto-zoomed to a selection (this works only if the other axis is a DateAxis or a CategoryAxis) and that the setting will be ignored if both X and Y axes are a ValueAxis, which is the case, but it works.

**Comment by zeroin** [comment] 2024-06-12 05:39
I indeed need to check why this happens with both axes being value axes, maybe it's a bug on our side.
As for the remaining problems, I could try to help, but I will need a codepen or jsfiddle where the issue could be reproduced.
BTW, you made a really interesting and good looking chart!

**Comment by martynasma** [comment] 2024-06-12 13:06
Fixed in [5.9.12](https://github.com/amcharts/amcharts5/releases/tag/5.9.12).

## [5.9.12] - 2024-06-12

### Changed
- `ClusteredPointSeries` now re-clusters points only when zoom level changes. This improves performance when paning/rotating the map.

### Fixed
- `NumberFormatter` would incorrectly round numbers smaller than 0 due to floating point issue in some cases.
- An error could occur when enabling drawing mode if there were previously disposed chart indicators.
- Truncated or wrapped labels were not properly sizing underline and line-through decorations.
- While wheel-zooming both X and Y axes simultaneously, the chart could fully zoom out in some cases.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2024-06-12 13:06 UTC
Labels: bug

**Comment by tapiamcclung** [comment] 2024-06-12 15:50
> I indeed need to check why this happens with both axes being value axes, maybe it's a bug on our side. As for the remaining problems, I could try to help, but I will need a codepen or jsfiddle where the issue could be reproduced. 

@zeroin Thanks! I will put together a pen and post it. 

> BTW, you made a really interesting and good looking chart!

Thanks!

@martynasma After refreshing and clearing cache (it now shows v. 5.9.12), it seems that at high zoom levels layers still come out of sync. It is likely to be a different issue than
> While wheel-zooming both X and Y axes simultaneously, the chart could fully zoom out in some cases.

because this seems to be working fine now. I'll see if it is still happening when I put together the pen and report back, and probably open a different issue. Thanks!
