### ISSUE TITLE
help me when after load success,

### ISSUE THREAD

**Issue by truongptit** [amcharts/amcharts5#721] opened 2022-12-15 04:32 UTC
![image](https://user-images.githubusercontent.com/36994973/207772946-d45a34e8-8016-4635-994f-1c309bee2073.png)

**Comment by martynasma** [comment] 2022-12-15 04:54
That error does not look like it's coming from amCharts.

If you think it's caused by amCharts, can you provide a runnable demo on CodePen or jsFiddle?

**Comment by truongptit** [comment] 2022-12-15 06:02
I apply amchart to my project, running jquery 3.4.1, 
initial run successfully
![image](https://user-images.githubusercontent.com/36994973/207784466-66c17f15-e8a3-4cc3-a5e5-e0c6ae61d1c5.png)

then I changed to another tab, and went back to the tab with amchart
https://user-images.githubusercontent.com/36994973/207772946-d45a34e8-8016-4635-994f-1c309bee2073.png

**Comment by martynasma** [comment] 2022-12-15 06:49
That does not give any additional details. Consider making a live demo.

**Comment by truongptit** [comment] 2022-12-15 07:00
this my video , thank you very much
https://1drv.ms/v/s!Ai-WCdA5hUVriLVzfYxoVExn_NeT9A?e=tgLlzh

**Comment by martynasma** [comment] 2022-12-15 07:05
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

The video does not help.

**Comment by truongptit** [comment] 2022-12-15 07:48
my function in my project call ajax as 
**$.ajax({
        url: "/Ticket/MnReportTicket",
        type: 'POST',
        success: function (html) {
            $("#ajax_loader").hide();
            $('#mainpageid').html(html);
        },
    });**

i change code in codepen
**document.getElementById('maindiv').innerHTML ='<div id="chartdiv"></div>';**

it doesn't crash like in my project  , on the video I shared
https://codepen.io/truongptit/pen/VwdoPOr

**Comment by truongptit** [comment] 2022-12-15 09:46
I found the error, if the function is used on the html document itself, it runs successfully.
But if it is called in another .js file, it will be like this

thank you very much!

**Comment by martynasma** [comment] 2022-12-15 10:59
Glad you worked it out.

Feel free to close this when ready.

**Comment by truongptit** [comment] 2022-12-15 11:10
thank you very much!

**Closed** 2022-12-15 11:10 UTC
Labels: question, off-topic
