### ISSUE TITLE
Issue with incorrect hours on the tooltip of a date axis

### ISSUE THREAD

**Issue by paulinebrisset** [amcharts/amcharts5#266] opened 2022-02-05 18:17 UTC
I have a problem with the tooltip on a Date axis. What I want to do is : 
- a XY chart, with a Date axis as x
- with data to publish every 6 hours (00:00, 06:00, 12:00, 18:00), sometimes data is null
- with a tooltip on the date axis to show the datas's hour
- with "connect : false" 

But I notice that even if the hour is properly printed on the data's tooltip, it's moved forward in the date axis tooltip, depending on the baseInterval I use. 

For baseInterval  timeUnit: "hour", count: 2  the hour is moved forward by one hour, 
for basteInterval timeUnit: "minute, count: 30, the hour is moved forward by 15 minutes. 
So I want to have baseInterval  timeUnit: "hour", count: 6, and the x axis's tooltip show 3 hours more than the real data. 

There is the codepen link : https://codepen.io/paulinebrisset/pen/GRONoRm

Could you help me to fix it or tell me where I am wrong ?

**Comment by martynasma** [comment] 2022-02-07 09:43
Duplicate of https://github.com/amcharts/amcharts5/issues/55

Please subscribe to updates on that issue.

**Closed by martynasma** 2022-02-07 09:43 UTC
