### ISSUE TITLE
How can I incrementally update ForceDirected?

### ISSUE THREAD

**Issue by lancegliser** [amcharts/amcharts5#230] opened 2022-01-21 21:03 UTC
I'm trying to get [incremental loading](https://www.amcharts.com/docs/v5/concepts/data/#Incremental_updates) working with [ForceDirected](https://www.amcharts.com/docs/v5/charts/hierarchy/force-directed/).

You can see that I have data, taken from the [example](https://www.amcharts.com/demos/force-directed-network/) loaded in console:
![image](https://user-images.githubusercontent.com/12085479/150598816-07dd94d9-856f-4ffd-8013-7ec3abce20bd.png)

I then run this code to try and remove an arbitrary vertex:

```ts
    series.data.each((datum, index) => {
      series.data.removeIndex(index);
      const filteredDatum = getFilteredHierarchicalData(
        [datum as ForceGraphSeriesDatum],
        contextMenuItem.datum,
        defaultSeriesSettings.seriesSettings.idField!
      ).shift();
      if (!filteredDatum) {
        // This works, everything is gone
        series.data.removeIndex(index);
        return;
      }

      // this blows up
      series.data.setIndex(index, filteredDatum);
    });
  };


const getFilteredHierarchicalData = (
  data: ForceGraphSeriesDatum[],
  toRemove: ForceGraphSeriesDatum,
  idField: string
): ForceGraphSeriesDatum[] =>
  data
    .filter((datum) => datum[idField] != toRemove[idField])
    .map((datum) => ({
      ...datum,
      children: datum.children
        ? getFilteredHierarchicalData(datum.children, toRemove, idField)
        : undefined,
    }));
```

But it throws an error in `checkBounds`:
```
"Error: Index out of bounds: 0
    at checkBounds (http://localhost:6007/vendors~main.iframe.bundle.js:34429:15)
    at ListData.value (http://localhost:6007/vendors~main.iframe.bundle.js:34673:13)
    at http://localhost:6007/main.iframe.bundle.js:1808:19
    at Object.each (http://localhost:6007/vendors~main.iframe.bundle.js:28082:9)
    at ListData.value (http://localhost:6007/vendors~main.iframe.bundle.js:34941:64)
    at removeNode (http://localhost:6007/main.iframe.bundle.js:1799:17)
    at HTMLUnknownElement.callCallback (http://localhost:6007/vendors~main.iframe.bundle.js:167938:14)
    at Object.invokeGuardedCallbackDev (http://localhost:6007/vendors~main.iframe.bundle.js:167987:16)
    at invokeGuardedCallback (http://localhost:6007/vendors~main.iframe.bundle.js:168049:31)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:6007/vendors~main.iframe.bundle.js:168063:25)"
```

Back in the callstack one, it runs `checkBounds` using this logic (sorry for the compiled js)
```js
    Object.defineProperty(List.prototype, "setIndex", {
        enumerable: false,
        configurable: true,
        writable: true,
        value: function (index, value) {
            checkBounds(index, this._values.length);
            var oldValue = this._values[index];
            // Do nothing if the old value and the new value are the same
            if (oldValue !== value) {
                this._values[index] = value;
                this._onSetIndex(index, oldValue, value);
            }
            return oldValue;
        }
    });
```

Which means the interesting bit is `ListData`'s `this._values.length` which is just an empty array `[]` so `length` is `0`. It's the same `series.data` we had before. But going up the call stack one more, it's been mutated to an empty value: `ListData {_values: Array(0), events: EventDispatcher, processor: undefined}`

Any idea what I might be doing wrong here?

**Comment by lancegliser** [comment] 2022-01-21 21:43
To be clear. I'm attempting to remove and add without having to redraw the entire graph as I hate the loading animation of them flying in.

**Comment by martynasma** [comment] 2022-01-24 06:37
Duplicate of https://github.com/amcharts/amcharts5/issues/31

Please subscribe to the above issue to be notified when/if we're going to implement incremental updates for hierarchy-based charts.

**Closed by martynasma** 2022-01-24 06:37 UTC
