### ISSUE TITLE
Period Selector does not show complete data on chart based on selected range

### ISSUE THREAD

**Issue by jaganathanb** [amcharts/amcharts5#802] opened 2023-02-14 08:24 UTC
**Bug description**

In the PeriodSelector [demo](https://www.amcharts.com/docs/v5/charts/stock/toolbar/period-selector/) given for AmChart 5, when i select 5D from the selector, i expect it should show 5 days of data in the chart. But it shows only 3 days of data.

Is there any setting to show the complete data for the selected data range?

[Codepen](https://codepen.io/team/amcharts/pen/popQjbv)

**Comment by martynasma** [comment] 2023-02-14 08:37
It does select 5 calendar days. However, since there are no data for the first 2 days, and the chart uses GaplessDateAxis, it looks like it's only selecting 3 days.

I think it's the right behavior, not a bug.

**Comment by jaganathanb** [comment] 2023-02-15 06:13
I have created new pen which has data for last 10 days. And still i see the issue. 

[Pen](https://codepen.io/jegadhu84/pen/JjajzZW)

**Comment by martynasma** [comment] 2023-02-15 06:53
OK, now that's weird. Thanks.

We'll need to look into it.

**Comment by martynasma** [comment] 2023-02-20 12:42
Fixed in [5.3.4](https://github.com/amcharts/amcharts5/releases/tag/5.3.4).

## [5.3.4] - 2023-02-20

### Added
- `cellWidth` read-only private setting added to `Axis`. Holds a distance in pixels between two grid lines. It might not be accurate as grid on `DateAxis` might not be at equal intervals.
- `getCellWidthPosition()` added to all axis types. Returns relative distance between two grid lines of the axis.

### Fixed
- HTML-based tooltip might produce a funky animation if it was displayed very close to the edge of the chart.
- `StockChart`'s X-axes from all panels not always were syncing properly between data updates.
- Fixing bug where click event was not dispatched on tooltips outside of the chart boundaries.
- Changing a color for a `LineSeries` in with a `StockChart` control was not changing its tooltip color.
- `GaplessDateAxis` was not taking into account missing dates when using `zoomToDates()` or `zoomToValues()` methods.
- When data grouping was on and data was changed, `ValueAxis` was zooming to incorrect position.
- Radial labels sometimes could get reversed when updating their settings.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2023-02-20 12:42 UTC
Labels: bug, in next release
