### ISSUE TITLE
Dual value axis adaptive y scale when chart wheelY is set to zoomX

### ISSUE THREAD

**Issue by cwooldridge1** [amcharts/amcharts5#533] opened 2022-08-09 16:56 UTC
My issue:
I discovered that when you have a value axis for both x and y and the chart settings for wheelY are set to 'zoomX' the auto zoom feature doesn't work as it does on date axes. I found [this post](https://github.com/amcharts/amcharts4/issues/1527) for amcharts4 where there was a similar question and your solution was to set it to a date axis and set the time to milliseconds so it gave the look of a value axis with the auto zoom functionality of a date axis. The issue I am having with this solution is that the date axis doesn't give the same smoothing ability that the value axis does and my output appears to look very choppy as such: 
![image](https://user-images.githubusercontent.com/85259389/183709889-64ce59f0-90ef-439c-8451-a31df51e8534.png)

My question: 
In amchart5 is there a way to get this auto zoom feature to work for dual value axes without adding event listens for axis range resizing and then iterating the data  to find the new zoom level? Or is there a way to change the date axis so the lines are smoothed/ not choppy as the above phot depicts

**Comment by martynasma** [comment] 2022-08-10 06:24
Duplicate of #516.

**Closed by martynasma** 2022-08-10 06:24 UTC

**Comment by cwooldridge1** [comment] 2022-08-10 20:00
Sorry I did not see that. However my question of: "is there a way to change the date axis so the lines are smoothed/ not choppy as the above photo depicts" remains as that would solve my issue. 
Thanks

**Comment by cwooldridge1** [comment] 2022-08-11 05:40
Adding my solution here:
```
    chart.plotContainer.events.on('wheel', func);
    chart.events.on('panended', func);
    chart.events.on('boundschanged', func);
```
Inside of the func callback, you should first find what data is currently in the x-axis zoom scope/visible x-range:
```
      const chartRelativeStartPosition = xAxis.get('start');
      const chartRelativeEndPosition = xAxis.get('end');
      const chartStartValue = xAxis.positionToValue(chartRelativeStartPosition);
      const chartEndValue = xAxis.positionToValue(chartRelativeEndPosition);
```

Once you have the start and end value of the current x-axis scope just search for/calculate the corresponding y value and zoom to those values:
`
      yAxis.zoomToValues(correspondingYValueStart, correspondingYValueEnd);
`
