### ISSUE TITLE
Treemap DrillDown change children color 

### ISSUE THREAD

**Issue by justine-mlss** [amcharts/amcharts5#600] opened 2022-09-05 10:17 UTC
Hello,

I've a question about Treemap : I have a drill down treemap and I want to set another color of children. But it doesn't work. 
When I drill down, children have the same color as parent.

Can you help me about this issue ?  

Here a testing code :  https://codepen.io/Justinemlss/pen/gOzbzPK

Thank you

**Comment by martynasma** [comment] 2022-09-06 04:24
Duplicate of: #596

**Closed by martynasma** 2022-09-06 04:24 UTC
Labels: duplicate, question
