### ISSUE TITLE
Pannable and Zoommable Force-directed Chart

### ISSUE THREAD

**Issue by elinagilevich** [amcharts/amcharts5#936] opened 2023-05-31 10:02 UTC
Hi, I'm just wondering is there any possibility in amCharts 5 to make pannable and zoomable container for Force-directed chart? 
Some nodes may not fit in the view (especially for large amount of data). And the only way to return them to the view is to drag them by the node.
Thank you in advance.

**Comment by martynasma** [comment] 2023-05-31 10:06
Duplicate of https://github.com/amcharts/amcharts5/issues/216. Please follow that issue.

**Closed by martynasma** 2023-05-31 10:06 UTC
